### ISSUE TITLE
brew install fails on latest version (1.88.76)

### ISSUE THREAD

**Issue by nudge** [pact-foundation/homebrew-pact-ruby-standalone#61]
brew install fails:

```
$  brew install pact-ruby-standalone

Error: pact-ruby-standalone: /usr/local/Homebrew/Library/Taps/pact-foundation/homebrew-pact-ruby-standalone/pact-ruby-standalone.rb:12: syntax error, unexpected tIDENTIFIER, expecting end
        puts "# Run "pact-mock-service help [COMMAND]"...
                     ^~~~
/usr/local/Homebrew/Library/Taps/pact-foundation/homebrew-pact-ruby-standalone/pact-ruby-standalone.rb:12: syntax error, unexpected tIDENTIFIER, expecting do or '{' or '('
... "# Run "pact-mock-service help [COMMAND]" (for more see htt...
...                           ^~~~
/usr/local/Homebrew/Library/Taps/pact-foundation/homebrew-pact-ruby-standalone/pact-ruby-standalone.rb:12: syntax error, unexpected tSTRING_BEG, expecting end
...ct-mock-service help [COMMAND]" (for more see https://github...
...                              ^
```

I opened PR #60 to fix the issue.

**Comment by alannichols** [comment]
Thank you for raising this PR. Not sure who to ask but is there any indication of when this will be reviewed / merged / released? As brewfile installs always pick up the most recent version this is breaking builds. It would be good to know any indication of timeframe as we are currently debating removing all of our pact dependencies from our project.

**Comment by nudge** [comment]
@surpher can you take a look at this issue? Thanks!

@alannichols This is also breaking our CI.
This is our workaround to install the previous version to get CI builds running again:
```
  # temporary workaround
  # brew tap pact-foundation/pact-ruby-standalone
  # brew install pact-ruby-standalone
  git clone https://github.com/pact-foundation/homebrew-pact-ruby-standalone /usr/local/Homebrew/Library/Taps/pact-foundation/homebrew-pact-ruby-standalone
  cd /usr/local/Homebrew/Library/Taps/pact-foundation/homebrew-pact-ruby-standalone
  git checkout 46944d68f6b0c4706e571e11ae35592a52c4b5ab
  HOMEBREW_NO_AUTO_UPDATE=1 brew install pact-ruby-standalone
```

Hope this helps!

**Comment by alannichols** [comment]
That's awesome thank you. Currently I've just removed pact from our project as it was blocking a release. I will try this workaround if the PR isn't merged. Ty for all of the help :D

**Comment by surpher** [comment]
Sorry 'bout that. Should've been fixed now. 

Run:
`brew update`
`brew upgrade pact-foundation/pact-ruby-standalone`
